name: CI

on:
  push:
    branches:
      - 'master'
      - 'create-pull-request/package-update'
    tags: '*'
  pull_request:

jobs:
  build:
    name: Page build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7' # Keep in sync with .github/workflows/pkg-update.yml
      - name: Install dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project --color=yes make.jl
