name: Update documentation dependencies
on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DOCUMENTER_KEY_NO_BASE64 }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7' # Keep in sync with .github/workflows/ci.yml
      - name: 'Pkg.update'
        run: |
          julia --project=. -e 'using Pkg; Pkg.update()'
          echo 'PKG_DIFF<<EOF' >> $GITHUB_ENV
          echo 'pkg> status --project --diff' >> $GITHUB_ENV
          julia --project=. -e 'using Pkg; Pkg.status(; mode=PKGMODE_PROJECT, diff=true)' >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo 'pkg> status --manifest --diff' >> $GITHUB_ENV
          julia --project=. -e 'using Pkg; Pkg.status(; mode=PKGMODE_MANIFEST, diff=true)' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: 'Create pull request'
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automatic Pkg.update()'
          branch: 'create-pull-request/package-update'
          author: 'GitHub <noreply@github.com>'
          body: |
            Automatic `Pkg.update()` with the following changes:
            ```
            ${{ env.PKG_DIFF }}
            ```
            A preview of the build will soon be available at <https://julialogging.github.io/previews/package-update/>.
          commit-message: |
            Automatic Pkg.update() with the following changes:

            ${{ env.PKG_DIFF }}
